language: python

os:
  - linux

sudo: off

addons:

  apt:
    packages:
      - python-numpy
      - python-scipy
      - gettext

python:
  - "3.8"
  - "3.9"
  - "3.10-dev"
  - "3.11-dev"

# command to install dependencies
install:
  - "pip install astropy"
  - "./configure"
  - "python setup.py install"

script:
  - crtwo2fits --help
