language: python

jobs:
  include:
    - os: linux
      dist: focal

sudo: off

addons:
  apt:
    packages:
      - python-numpy
      - python-scipy
      - gettext

python:
  - "3.8"
  - "3.9"
  - "3.10-dev"
  - "3.11-dev"

# command to install dependencies
install:
  - "./configure"
  - "pip install -r requirements.txt"
  - "pip install ."

script:
  - crtwo2fits --help

